### PR TITLE
Add background, and make everything look really nice.

### PR DESCRIPTION
**Pull request by sophia-angel**
I left a alternate background (background1.css) which can be imported by editing the CSS multiplexer, and I also left you a API that can allow for video backgrounding AS the canvas.

### CODE REVIEW

**Review by eeeyrie — CHANGES_REQUESTED** [review]
loader.js is unnecessary and will be detrimental to mobile compatibility, multiplexmii.css imports too many unused code, i don't think the other backgrounds will be really used because this is a **kirby tv channel** revival at the moment, the border thing is way too bulky (literally uses iframe for a seperation line) and unnecessary, and session seed is useless

**Comment by b1ue64** [comment]
actually multiplexmii adds way too much stuff that's not even used

**Comment by b1ue64** [comment]
also session seed isn't needed lo-

**Comment by b1ue64** [comment]
all in all, the current thing is good enough

**Comment by sophia-angel** [comment]
Yeah, I agree that nothing really fits in with the scope.

**Pull request closed without merging**
